###

# curl -X POST http://localhost:5001/api/auth/login
#    -H "Content-Type: application/json"
#    -d '{"username": "testuser", "password": "password123"}'
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
  "username": "john_doe",
  "password": "password123"
}

###


