import { Platform } from 'react-native';
import DeviceInfo from 'react-native-device-info';

/**
 * API Configuration
 *
 * This configuration now automatically detects:
 * - iOS Simulator → uses localhost
 * - Android Emulator → uses 10.0.2.2
 * - Physical Devices → uses dynamically detected IP from ip-config.json or RENDER_APP_URL env var
 *
 * To use Render deployment:
 *   1. Deploy backend to Render (see RENDER_QUICK_START.md)
 *   2. Set environment variable: RENDER_APP_URL=https://your-app-name.onrender.com
 *   3. Rebuild APK: npm run build-android-release
 *   Example: RENDER_APP_URL=https://stt-proto-1.onrender.com npm run build-android-release
 *
 * To update the backend IP for local physical devices, run:
 *   npm run detect-ip
 * or
 *   node scripts/detect-ip.js
 */

// Import dynamically detected IP (generated by scripts/detect-ip.js)
let HOST_IP = '192.168.68.101'; // Fallback IP
try {
    const ipConfig = require('./ip-config.json');
    HOST_IP = ipConfig.HOST_IP;
} catch (error) {
    console.warn('⚠️ Could not load ip-config.json. Run "npm run detect-ip" to generate it.');
}

// Import backend configuration
let backendConfig: any = {
    environment: 'development',
    backends: {
        development: { url: 'http://192.168.68.101:5001', description: 'Local backend' },
        live: { url: 'https://stt-proto-1.onrender.com', description: 'Live Render backend' }
    },
    current: 'development'
};

try {
    const config = require('./backend-config.json');
    backendConfig = config;
} catch (error) {
    console.warn('⚠️ Could not load backend-config.json. Using defaults.');
}

// API Configuration
const API_PORT = 5001;

// Auto-detect environment and choose appropriate backend URL
const getBaseUrl = (): string => {
    // Priority 1: Check backend-config.json for current environment
    if (backendConfig.current && backendConfig.backends[backendConfig.current]) {
        const url = backendConfig.backends[backendConfig.current].url;
        console.log(`🚀 Using ${backendConfig.current} backend:`, url);
        return url;
    }

    // Priority 2: Check if Render URL is set (for production APK builds)
    // Set via: RENDER_APP_URL=https://your-app-name.onrender.com npm run build-android-release
    const renderUrl = process.env.RENDER_APP_URL;
    if (renderUrl) {
        console.log('🚀 Using Render backend:', renderUrl);
        return renderUrl;
    }

    // Priority 4: Auto-detect based on emulator/device
    // Check if running on emulator/simulator
    const isEmulator = DeviceInfo.isEmulatorSync();

    if (isEmulator) {
        // Running on emulator/simulator
        if (Platform.OS === 'android') {
            // Android Emulator uses special IP to access host machine
            return `http://10.0.2.2:${API_PORT}`;
        } else {
            // iOS Simulator can use localhost
            return `http://localhost:${API_PORT}`;
        }
    } else {
        // Running on physical device - use detected local network IP
        return `http://${HOST_IP}:${API_PORT}`;
    }
};

export const API_CONFIG = {
    BASE_URL: getBaseUrl(),
    AUTH_URL: `${getBaseUrl()}/api/auth`,
    CONVERSATION_URL: `${getBaseUrl()}/api/conversation`,
    TIMEOUT: 30000, // 30 seconds
    HOST_IP, // Expose for debugging
    API_PORT, // Expose for debugging
};

// Helper to check current configuration
export const getApiInfo = () => ({
    baseUrl: API_CONFIG.BASE_URL,
    platform: Platform.OS,
    hostIp: HOST_IP,
    port: API_PORT,
});

// Log configuration on import (helpful for debugging)
if (__DEV__) {
    console.log('API Configuration:', getApiInfo());
}