import { Platform } from 'react-native';
import DeviceInfo from 'react-native-device-info';

/**
 * API Configuration
 *
 * This configuration now automatically detects:
 * - iOS Simulator → uses localhost
 * - Android Emulator → uses 10.0.2.2
 * - Physical Devices → uses dynamically detected IP from ip-config.json
 *
 * To update the backend IP for physical devices, run:
 *   npm run detect-ip
 * or
 *   node scripts/detect-ip.js
 */

// Import dynamically detected IP (generated by scripts/detect-ip.js)
let HOST_IP = '192.168.68.101'; // Fallback IP
try {
    const ipConfig = require('./ip-config.json');
    HOST_IP = ipConfig.HOST_IP;
} catch (error) {
    console.warn('⚠️ Could not load ip-config.json. Run "npm run detect-ip" to generate it.');
}

// API Configuration
const API_PORT = 5001;

// Auto-detect environment and choose appropriate backend URL
const getBaseUrl = (): string => {
    // Check if running on emulator/simulator
    const isEmulator = DeviceInfo.isEmulatorSync();

    if (isEmulator) {
        // Running on emulator/simulator
        if (Platform.OS === 'android') {
            // Android Emulator uses special IP to access host machine
            return `http://10.0.2.2:${API_PORT}`;
        } else {
            // iOS Simulator can use localhost
            return `http://localhost:${API_PORT}`;
        }
    } else {
        // Running on physical device - use detected local network IP
        return `http://${HOST_IP}:${API_PORT}`;
    }
};

export const API_CONFIG = {
    BASE_URL: getBaseUrl(),
    AUTH_URL: `${getBaseUrl()}/api/auth`,
    CONVERSATION_URL: `${getBaseUrl()}/api/conversation`,
    TIMEOUT: 30000, // 30 seconds
    HOST_IP, // Expose for debugging
    API_PORT, // Expose for debugging
};

// Helper to check current configuration
export const getApiInfo = () => ({
    baseUrl: API_CONFIG.BASE_URL,
    platform: Platform.OS,
    hostIp: HOST_IP,
    port: API_PORT,
});

// Log configuration on import (helpful for debugging)
if (__DEV__) {
    console.log('API Configuration:', getApiInfo());
}